### PR TITLE
Fix package.json build script

### PR DESCRIPTION
**Pull request by mattferrin**
Installed locally and had minor changes.

### CODE REVIEW

**Comment by tuckerconnelly** [comment]
Hey Matt, thanks for the PR

Looks like this is just stylistic changes? Just seeing tabs parentheses in the files changed.

**Comment by mattferrin** [comment]
@tuckerconnelly The build script failed and I was not able to "compile" without these changes.

**Comment by tuckerconnelly** [comment]
What was the error?

**Comment by mattferrin** [comment]
It was a long time ago and I didn't screen capture, but it was only multi-line JSX and inconsistent indentation linting that blocked the build script, as I recall.

**Comment by mattferrin** [comment]
Makes no sense that `View` is just as much "multi-line" as `Body2` was, but it complained and required me to make only those edits on my system to run the script, so I was just thinking others would hit the same small snag if I didn't help a little.

**Comment by tuckerconnelly** [comment]
Alright if eslint is happy I'm happy. Thanks a bunch man!

**Comment by mattferrin** [comment]
Thank you.

**Pull request merged**
