### PR TITLE
Added icons to web. Did not tackle styles to minimize commit complexity.

### PR DESCRIPTION
**Pull request by mattferrin**
Meant to be as simple as possible. Attempted to limit complexity and diff size, so more could be done after, if this is accepted.

### CODE REVIEW

**Comment by tuckerconnelly** [comment]
They thanks for the PR :) Don't icons already work on web? If you include the `<WebStyles />` component?

**Comment by mattferrin** [comment]
I might have missed something. This didn't work for me in "evergreen" Chrome:

```js
import {
  App
} from './index/app'
import { WebStyles } from 'carbon-ui'
import React from 'react'
import {
  AppRegistry
} from 'react-native'

const AppWithStyles = () => <App><WebStyles /></App>
AppRegistry.registerComponent('AnonymousAppName', () => AppWithStyles)
AppRegistry.runApplication('AnonymousAppName', { rootTag: document.getElementById('react_root') })
```

I followed these instructions and made these small changes to support it.

**Comment by mattferrin** [comment]
Just double checked MaterialIcons-Regular.ttf in Xcode. I'll need to wait till I have more time to check if maybe `<WebStyles />` isn't rendering, but the fonts are working to the best of my knowledge as everything runs fine.

**Comment by tuckerconnelly** [comment]
Closing for inactivity! Lemme know if you still wanna merge this

**Comment by mattferrin** [comment]
The icons did not work for me without it, but it's good that you are closing this because I haven't had time to look at `<WebStyles />` myself. The momentum behind NativeBase seems strong, so I've started to use that more myself.

It's not ideal though because it doesn't support web yet and I have to duplicate more code to support both. Plus, I like Material Design on iOS :)

**Pull request closed without merging**
